name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Find gradlew location
        id: find-gradle
        run: |
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          echo "Gradle wrapper found at: $GRADLEW_PATH"
          echo "GRADLEW_DIR=$(dirname "$GRADLEW_PATH")" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x "$GRADLEW_DIR/gradlew"

      - name: Build Debug APK
        run: |
          c
